name: Create PR from Pad Entry

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  run_go_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Go program
        run: go run ./pad2gh/main.go
